logging {
  debug: off
  to_syslog: yes
}

nodelist {
  node {
    name: MT2ThinkCentre
    nodeid: 1
    quorum_votes: 1
    ring0_addr: 10.0.10.11
  }
  node {
    name: Serwer        
    nodeid: 2
    quorum_votes: 1
    ring0_addr: 10.0.10.12
  }
}

quorum {
  device {
    model: net
    net {
      algorithm: ffsplit
      host: 10.0.90.1
      tls: on
    }
    votes: 1
  }
  provider: corosync_votequorum
}

totem {
  cluster_name: Home-Lab
  config_version: 11
  interface {
    linknumber: 0
  }
  ip_version: ipv4-6
  link_mode: passive
  secauth: on
  version: 2
}

